name: Build and Push Containerd Image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'kafka-connect/**'
      - .github/kafka-connect.yml

env:
  IMAGE_NAME: kafka-connect
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: kafka-connect
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            CONTAINERD_VERSION=1.5.5

      - name: Clean up
        run: |
          docker buildx rm
