name: Build kafdrop-aws-msk-iam-auth

on:
  push:
    branches:
      - main
    paths:
      - 'nentangso/kafdrop-aws-msk-iam-auth/**'
      - .github/workflows/kafdrop-aws-msk-iam-auth.yml
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: {}

env:
  IMAGE_NAME: "${{ secrets.DOCKER_ORG }}/kafdrop-aws-msk-iam-auth"
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: nentangso/kafdrop-aws-msk-iam-auth
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
          build-args: |
            CONTAINERD_VERSION=1.5.5

      - name: Clean up
        run: |
          docker buildx rm
